### ISSUE TITLE
Autolayout Fill Issues

### ISSUE THREAD

**Issue by tinbacme** [EightShapes/specs-plugin-feedback#40]
### Description
There is an issue when I use auto layout fill for a component the component either gets shorter in annotation or gets cut off.
{A clear and concise description of what the bug is}

### Steps to reproduce

The first screen I annotate how the component was build. Let me know if there is anything I need to clarify. 

See Screenshot 
![Frame 2018775578](https://user-images.githubusercontent.com/64810896/219471777-ffcc7315-56a6-4979-90ca-428523626946.png)

See Screenshot
![SCR-20230216-gi9](https://user-images.githubusercontent.com/64810896/219472431-70512560-17a8-46f1-b046-e5cf0d38339d.png)

### Expected behavior

{A clear and concise description of what you expected to happen}

When using the plugin, the sizing of all component visually stays the same, with the annotation on the right maybe listed as fill.

### Console log

{Paste the text or screenshot of error displayed in the console log. To open the console log in Figma, select Plugins > Development > Open console _before_ running the plugin to reproduce the error}

### Additional context

{Add any other context about the problem here}

**Comment by nathanacurtis** [comment]
@tinbacme Well that's fascinating. I've not seen instances of resetting of vertical and/or horizontal resizing attributes when cloning the instance or frame into the specs frames. It appears that the `Example` frame layer is reseting to `Hug` or something at that point. Any chance you could provide a View-only Figma link to _just_ the examples in your screenshots so that I can try to reproduce the error?

**Comment by tinbacme** [comment]
Sure! Here it is https://www.figma.com/file/GQSvjKOw1npFqPUXEmdN6c/EightShapes-Specs-(Community)?node-id=0%3A1&t=DJJIj73gpQvkCQ0U-1

@nathanacurtis

**Comment by nathanacurtis** [comment]
@tinbacme I've spent about an hour using your helpful sample assets, and haven't been able to determine the nuance of what's causing your display to squish. Autolayout resizing properties can be tricky, and cloning your example into the spec process is producing results that I can't yet predictably diagnose. I'm going to spend more time tinkering in the days to come.

For now, note that if you temporarily set horizontal resizing=`Hug` on the top level frame, the spec output is likely consistent with what you'd expect. Imperfect, but a workaround for now.

**Comment by tinbacme** [comment]
No worries, that's good to know. Thanks for the tips on the workaround. 
Either way great work, I appreciate this a lot. Your plugin has made my life so much easier. 

Thanks, 
Tin

**Comment by nathanacurtis** [comment]
From #48 by @inetwebguy When running the plugin, the output of the specs (Anatomy) is not honoring the width of the component
Steps to reproduce
Create a primary container and apply an Auto Layout with a fixed width (in my case it's 720px)
Add content to the auto layout
Run Specs plugin
Expected behavior
Anatomy would reflect visual (width) of the component

Other
Changing the width of the primary container's auto layout from "Fixed" to "Hug" displays the expected behavior.

**Comment by nathanacurtis** [comment]
@tinbacme While fixing #40, detected another issue #49.

**Comment by nathanacurtis** [comment]
Fixed and published as new plugin version.
