### ISSUE TITLE
Show Tokens from Tokens Studio attached to a component.

### ISSUE THREAD

**Issue by snak10** [EightShapes/specs-plugin-feedback#44]
**Is your feature request related to a problem? Please describe.**
I need to change all the styles to tokens once it's done.
I would love to see Design Tokens that were previously attached to the layers using Figma tokens in the hand-off specs that the plugins generate.

**Describe the solution you'd like**
Once I start the spec plugin on the component, it should identify the tokens attached to the individual layers and spec them out for me instead of using the Figma Styles

**Describe alternatives you've considered**
Simply rewriting the styles to tokens 

**Additional context**
This is how I currently do it.
![image](https://user-images.githubusercontent.com/19668787/219916002-b758f7b5-94b3-4014-b437-a596971729c7.png)

And this is an simple example on how I'm planning on using the specs plugin
![image](https://user-images.githubusercontent.com/19668787/219916907-64c9db34-4c2d-4717-abb4-d584212c7cb7.png)

**Thanks for this plugin, it's amazing ❤**

**Comment by nathanacurtis** [comment]
@snak10 I've [inquired with the Tokens Studio team using their product's Slack](https://tokens-studio.slack.com/archives/C02HN8GAZV4/p1676985011704119) to discern what if any possible integration there may be.

**Comment by nathanacurtis** [comment]
Tokens Studio exposes applied tokens using [Shared Data](https://docs.tokens.studio/contributing/shared-data).

**Comment by wolfXDnet** [comment]
@nathanacurtis I'm currently working on a plugin that would do pretty much the same as yours but is centered around annotating tokens. I must admit that EightShapes is way ahead, but (IMHO) when it comes to tokens the complexity might pile up a bit. It would be great if we could exchange a bit on that topic...

**Comment by nathanacurtis** [comment]
@wolfXDnet Can you provide more details about what you'd annotate? What would an output look like? What attributes would it describe? What would it be run against (a Styles set? a Tokens Studio tokens collection, ...)?

**Comment by wolfXDnet** [comment]
There are two main use cases. First one is to document components which would cover the annotation similar to your approach. I'm using a table like depiction for this to annotate the properties (e.g. paddings, spacing) of all subsequent nodes that have tokens applied. I'm collecting token name, the raw value and the actual value.
Problem with that is that it can bloat the annotation because this includes subsequent instances as well. So I'm looking into only annotating tokens that are unique or have changed from its main component.
Styles are basically treated the same way.
Second use case is to focus on used components including the selects properties and manual overrides when documenting entire screens.

**Comment by nathanacurtis** [comment]
@snak10 @wolfXDnet Note that I've completed my MVP of Token Studio integration, whose release is now dependent on my finalizing how to add payments (it'll require a small subscription fee). I'm hoping that launches in the week(s) to come, so I'm going to close this issue.

Here's a screenshot of what the output looks like... 

![Image](https://github.com/EightShapes/specs-plugin-feedback/assets/1165904/489d06c0-ceff-493e-82e6-116a039b04eb)

**Comment by snak10** [comment]
This is amazing!! Can't wait to get it! Thanks for building it, @nathanacurtis !
