### ISSUE TITLE
Long text lines do not wrap

### ISSUE THREAD

**Issue by henrich321** [EightShapes/specs-plugin-feedback#51]
### Description

It could be considered a feature request -- if you have a very long text field (say some descriptive text) the plugin shows it all on one line blowing out the formatting for everything else.  E.g.

![image](https://user-images.githubusercontent.com/103463229/221705313-a4835f3b-77c1-4c52-897c-e4a071752de0.png)

**Comment by nathanacurtis** [comment]
@henrich321 Thanks for submitting, and I'd not thought of this one.

Quick fix for you: override the default by naming the layer something shorter than the character value (your long string). 

I'm not sure if I'll fix this, since choosing the length to trim a layer name could be an arbitrary choice. I'll get feedback from some of my trusted advisors. Thanks.
